export const LEFT_SIDEBAR_SHOW = 'LEFT_SIDEBAR_SHOW'
export const LEFT_SIDEBAR_HIDE = 'LEFT_SIDEBAR_HIDE'

export const UNVERIFYED_USER_ADD = 'UNVERIFYED_USER_ADD'
export const VERIFYED_USER_ADD = 'VERIFYED_USER_ADD'

//Thunk constants

export const SET_THUNK_REQUEST_REGISTERED_USERS = 'SET_THUNK_REQUEST_REGISTERED_USERS'
export const VIDEO_PREVIEWS_THUNK = 'VIDEO_PREVIEWS_THUNK'
export const COMMENTS_VIDEO_THUNK = 'COMMENTS_VIDEO_THUNK'
export const USERS_DICTIONARY = 'USERS_DICTIONARY'
export const GET_VIDEO = 'GET_VIDEO'
export const ERROR_API_PROCESSING = 'ERROR_API_PROCESSING'
export const IS_USER_TOKEN = 'IS_USER_TOKEN'
export const IS_VERIFYED_USER = 'IS_VERIFYED_USER'
export const VIDEO_OWNER_USER = 'VIDEO_OWNER_USER'
export const GET_PRIVATE_ROOMS = 'GET_PRIVATE_ROOMS'
export const GET_PRIVATE_MESSAGES = 'GET_PRIVATE_MESSAGES'

export const GET_PRIVATE_ROOMS_MULTI_USERS = 'GET_PRIVATE_ROOMS_MULTI_USERS'


// operating with Base Constants
export const POST_USER_ROOM = 'POST_USER_ROOM'
export const POST_USER_MESSAGE = 'POST_USER_MESSAGE'
export const PUT_TO_BASE = 'PUT_TO_BASE'
export const DELETE_FROM_BASE = 'DELETE_FROM_BASE'
export const POST_TO_BASE = 'POST_TO_BASE'
export const GET_COMMENTS_WITH_QUOTATION = 'GET_COMMENTS_WITH_QUOTATION'
export const POST_COMMENTS_WITH_QUOTATION = 'POST_COMMENTS_WITH_QUOTATION'
export const POST_TO_BASE_MEDIA = 'POST_TO_BASE_MEDIA'
export const CREATE_EMPTY_USER = 'CREATE_EMPTY_USER'
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD'
export const CREATE_NEW_VIDEO = 'CREATE_NEW_VIDEO'
export const PUT_NEW_USER_CREATE_DATA = 'PUT_NEW_USER_CREATE_DATA'

// WS contants
export const SET_WS = 'SET_WS'

export const GET_USER_AVATAR = 'GET_USER_AVATAR'